### ISSUE TITLE
Please remove this. -Spotify IP Enforcement

### ISSUE THREAD

**Issue by configari** [kero3009destiny/spotify-sources#1]
You'll be hearing about our DMCA strike about this repository on Github.

- Spotify IP Enforcement & Hackerone

**Comment by kero3009destiny** [comment]
![image](https://user-images.githubusercontent.com/26773027/179354914-f7478723-2ec3-4a47-b5db-1543c70edbac.png)

**Comment by configari** [comment]
Okay, we'll be removing the DMCA request.

Regards,
Spotify IP Enforcement & Hackerone
